# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_spopt_wrappers", use_symbols = TRUE, package_name = "spopt")

#' @docType package
#' @usage NULL
#' @useDynLib spopt, .registration = TRUE
NULL

#' Compute Euclidean distance matrix (Rust)
#' @keywords internal
rust_distance_matrix_euclidean <- function(x1, y1, x2, y2) {
  .Call("wrap__rust_distance_matrix_euclidean", x1, y1, x2, y2, PACKAGE = "spopt")
}

#' Compute Manhattan distance matrix (Rust)
#' @keywords internal
rust_distance_matrix_manhattan <- function(x1, y1, x2, y2) {
  .Call("wrap__rust_distance_matrix_manhattan", x1, y1, x2, y2, PACKAGE = "spopt")
}

#' Compute minimum spanning tree (Rust)
#' @keywords internal
rust_mst <- function(i, j, weights, n) {
  .Call("wrap__rust_mst", i, j, weights, n, PACKAGE = "spopt")
}

#' Check if graph is connected (Rust)
#' @keywords internal
rust_is_connected <- function(i, j, n) {
  .Call("wrap__rust_is_connected", i, j, n, PACKAGE = "spopt")
}

#' Find connected components (Rust)
#' @keywords internal
rust_connected_components <- function(i, j, n) {
  .Call("wrap__rust_connected_components", i, j, n, PACKAGE = "spopt")
}

#' Solve SKATER regionalization (Rust)
#' @keywords internal
rust_skater <- function(attrs, adj_i, adj_j, n_regions, floor_var, floor_value, seed) {
  .Call("wrap__rust_skater", attrs, adj_i, adj_j, n_regions, floor_var, floor_value, seed, PACKAGE = "spopt")
}

#' Solve P-Median problem (Rust)
#' @keywords internal
rust_p_median <- function(cost_matrix, weights, n_facilities) {
  .Call("wrap__rust_p_median", cost_matrix, weights, n_facilities, PACKAGE = "spopt")
}

#' Solve LSCP problem (Rust)
#' @keywords internal
rust_lscp <- function(cost_matrix, service_radius) {
  .Call("wrap__rust_lscp", cost_matrix, service_radius, PACKAGE = "spopt")
}

#' Solve MCLP problem (Rust)
#' @keywords internal
rust_mclp <- function(cost_matrix, weights, service_radius, n_facilities) {
  .Call("wrap__rust_mclp", cost_matrix, weights, service_radius, n_facilities, PACKAGE = "spopt")
}

#' Solve P-Center problem (Rust)
#' @keywords internal
rust_p_center <- function(cost_matrix, n_facilities) {
  .Call("wrap__rust_p_center", cost_matrix, n_facilities, PACKAGE = "spopt")
}

#' Solve P-Dispersion problem (Rust)
#' @keywords internal
rust_p_dispersion <- function(distance_matrix, n_facilities) {
  .Call("wrap__rust_p_dispersion", distance_matrix, n_facilities, PACKAGE = "spopt")
}

#' Solve Max-P regionalization problem (Rust)
#' @keywords internal
rust_max_p <- function(attrs, threshold_var, threshold, adj_i, adj_j, n_iterations, n_sa_iterations, cooling_rate, tabu_length, seed) {
  .Call("wrap__rust_max_p", attrs, threshold_var, threshold, adj_i, adj_j, n_iterations, n_sa_iterations, cooling_rate, tabu_length, seed, PACKAGE = "spopt")
}
